# Generated by Django 6.0.3 on 2026-04-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='django-slug', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
